AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: xChat App Description

Globals:
  Function:
    Timeout: 10
    MemorySize: 128

Resources:
  ChatGptEchoFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ChatGptEchoFunction
      Handler: chat.xchat.ChatGptEchoFunction::handleRequest
      Runtime: java11
      Architectures:
        - x86_64
      MemorySize: 512
      Environment:
        Variables:
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1
          OPENAI_ORG_ID: org-hjmTx18GgDpomxMwhp1Gs4rP
          WHATSAPP_PHONE_ID: 106487262422291
          DYNAMODB_TABLE_NAME: users_data
  WhatsappWebhookVerificationFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: WhatsappWebhookVerificationFunction
      Handler: chat.xchat.WhatsappWebhookVerificationFunction::handleRequest
      Runtime: java11
      Architectures:
        - x86_64
      MemorySize: 512
      Environment:
        Variables:
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1
          WEBHOOK_VERIFICATION_TOKEN: VERIFY_TOKEN
  TwilioSmsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: TwilioSmsFunction
      Handler: chat.xchat.TwilioSmsFunction::handleRequest
      Runtime: java11
      Architectures:
        - x86_64
      MemorySize: 512
      Environment:
        Variables:
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1
          OPENAI_ORG_ID: org-hjmTx18GgDpomxMwhp1Gs4rP
  UserRegistrationFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: UserRegistrationFunction
      Handler: chat.xchat.UserRegistrationFunction::handleRequest
      Runtime: java11
      Architectures:
        - x86_64
      MemorySize: 512
      Environment:
        Variables:
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1
          DYNAMODB_TABLE_NAME: users_data
          WHATSAPP_PHONE_ID: 106487262422291
  LoopMessageIMessagesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: LoopMessageIMessagesFunction
      Handler: chat.xchat.LoopMessageIMessagesFunction::handleRequest
      Runtime: java11
      Architectures:
        - x86_64
      MemorySize: 512
      Environment:
        Variables:
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1
          DYNAMODB_TABLE_NAME: users_data
          SENDER_NAME: sandbox.loopmessage@imsg.tel

Outputs:
  ChatGptEchoFunction:
    Description: "ChatGpt Echo Lambda Function ARN"
    Value: !GetAtt ChatGptEchoFunction.Arn
  ChatGptEchoFunctionIamRole:
    Description: "Implicit IAM Role created for ChatGpt Echo function"
    Value: !GetAtt ChatGptEchoFunctionRole.Arn
